import 'package:intl/intl.dart';

class AppLocalizations {
  static const Map<String, Map<String, String>> translations = {
    'tr': {
      'app_title': 'Namaz Vakitleri',
      'fajr': 'İmsak',
      'sunrise': 'Güneş',
      'dhuhr': 'Öğle',
      'asr': 'İkindi',
      'maghrib': 'Akşam',
      'isha': 'Yatsı',
      'settings': 'Ayarlar',
      'location': 'Konum',
      'qibla': 'Kibe',
      'search_city': 'Şehir Ara',
      'nearby_mosques': 'Yakındaki Camiler',
      'prayer_time_label': 'Vaktine',
      'iftar_time': 'İftar vaktine',
      'theme': 'Tema',
      'language': 'Dil',
      'notifications': 'Bildirimler',
      'enable_adhan': 'Ezan Sesini Aç',
      'prayer_notifications': 'Namaz Saati Bildirimleri',
      'system': 'Sistem',
      'light': 'Açık',
      'dark': 'Koyu',
      'hour': 'sa',
      'minute': 'dk',
      'second': 'sn',
      'cancel': 'İptal',
      'search': 'Ara',
      'loading': 'Yükleniyor...',
      'allow': 'İzin Ver',
      'open_settings': 'Ayarları Aç',
      'notification_imsak': 'İmsak namaz vakti',
      'notification_sunrise': 'Güneş vakti',
      'notification_noon': 'Öğle namaz vakti',
      'notification_afternoon': 'İkindi namaz vakti',
      'notification_sunset': 'Akşam namaz vakti',
      'notification_night': 'Yatsı namaz vakti',
      'adhan_enabled': 'Ezan Sesi Açık',
      'adhan_disabled': 'Ezan Sesi Kapalı',
      'notification_enabled': 'Bildirim Açık',
      'notification_disabled': 'Bildirim Kapalı',
      'notification_settings': 'Bildirim Ayarları',
    },
    'en': {
      'app_title': 'Prayer Times',
      'fajr': 'Fajr',
      'sunrise': 'Sunrise',
      'dhuhr': 'Dhuhr',
      'asr': 'Asr',
      'maghrib': 'Maghrib',
      'isha': 'Isha',
      'settings': 'Settings',
      'location': 'Location',
      'qibla': 'Qibla',
      'search_city': 'Search City',
      'nearby_mosques': 'Nearby Mosques',
      'prayer_time_label': 'Prayer Time',
      'iftar_time': 'Time to Iftar',
      'theme': 'Theme',
      'language': 'Language',
      'notifications': 'Notifications',
      'enable_adhan': 'Enable Adhan Sound',
      'prayer_notifications': 'Prayer Notifications',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'hour': 'hr',
      'minute': 'min',
      'second': 'sec',
      'cancel': 'Cancel',
      'search': 'Search',
      'loading': 'Loading...',
      'allow': 'Allow',
      'open_settings': 'Open Settings',
      'notification_imsak': 'Time for Fajr prayer',
      'notification_sunrise': 'Sunrise time',
      'notification_noon': 'Time for Dhuhr prayer',
      'notification_afternoon': 'Time for Asr prayer',
      'notification_sunset': 'Time for Maghrib prayer',
      'notification_night': 'Time for Isha prayer',
      'adhan_enabled': 'Adhan Sound Enabled',
      'adhan_disabled': 'Adhan Sound Disabled',
      'notification_enabled': 'Notifications Enabled',
      'notification_disabled': 'Notifications Disabled',
      'notification_settings': 'Notification Settings',
    },
    'ar': {
      'app_title': 'مواقيت الصلاة',
      'fajr': 'الفجر',
      'sunrise': 'شروق الشمس',
      'dhuhr': 'الظهر',
      'asr': 'العصر',
      'maghrib': 'المغرب',
      'isha': 'العشاء',
      'settings': 'الإعدادات',
      'location': 'الموقع',
      'qibla': 'القبلة',
      'search_city': 'البحث عن المدينة',
      'nearby_mosques': 'المساجد القريبة',
      'prayer_time_label': 'وقت الصلاة',
      'iftar_time': 'وقت الإفطار',
      'theme': 'المظهر',
      'language': 'اللغة',
      'notifications': 'الإخطارات',
      'enable_adhan': 'تفعيل صوت الأذان',
      'prayer_notifications': 'إخطارات وقت الصلاة',
      'system': 'النظام',
      'light': 'فاتح',
      'dark': 'داكن',
      'hour': 'ساعة',
      'minute': 'دقيقة',
      'second': 'ثانية',
      'cancel': 'إلغاء',
      'search': 'بحث',
      'loading': 'جاري التحميل...',
      'allow': 'السماح',
      'open_settings': 'افتح الإعدادات',
      'notification_imsak': 'حان وقت صلاة الفجر',
      'notification_sunrise': 'وقت شروق الشمس',
      'notification_noon': 'حان وقت صلاة الظهر',
      'notification_afternoon': 'حان وقت صلاة العصر',
      'notification_sunset': 'حان وقت صلاة المغرب',
      'notification_night': 'حان وقت صلاة العشاء',
      'adhan_enabled': 'صوت الأذان مفعل',
      'adhan_disabled': 'صوت الأذان معطل',
      'notification_enabled': 'الإخطارات مفعلة',
      'notification_disabled': 'الإخطارات معطلة',
      'notification_settings': 'إعدادات الإخطارات',
    },
  };

  static String translate(String key, String locale) {
    return translations[locale]?[key] ?? translations['en']?[key] ?? key;
  }

  static String getLocale(String? preferredLanguage) {
    if (preferredLanguage != null && translations.containsKey(preferredLanguage)) {
      return preferredLanguage;
    }

    final String systemLocale = Intl.systemLocale.split('_')[0].toLowerCase();
    if (translations.containsKey(systemLocale)) {
      return systemLocale;
    }

    return 'en';
  }

  static bool isRTL(String locale) => locale == 'ar';
}
